#' Reconstruct a Triangular Mesh from a 3D Point Cloud
#'
#' Reconstructs a triangular surface from a 3D point cloud using linear binning and
#' Marching Cubes, and returns the result as a `mesh3d` object.
#'
#' @param panel A numeric matrix or data frame with three columns containing the X,
#' Y, and Z coordinates of the point cloud.
#' @param resolNbin A numeric vector of length three defining the approximate binning
#' resolution in the X, Y, and Z directions. Default is `c(4, 4, 2)`.
#' @param meshCad Optional `mesh3d` object used as a reference for the spatial coverage
#' of the reconstructed surface. Default is `NULL`.
#' @param zeroBorder Logical. If `TRUE`, adds a zero-valued layer around the X and Z
#' limits before surface extraction. Default is `FALSE`.
#' @param kFactor Numeric factor used to determine the tolerance for removing low-density
#' nodes. If `NULL`, it is selected automatically. Default is `NULL`.
#' @param truncFactor Numeric factor used to truncate high-density node weights. Default
#' is `3.5`.
#' @param levelFactor Numeric factor used to define the isosurface extraction level.
#' Default is `0.99`.
#' @param coverageTol Numeric value between 0 and 1 defining the minimum spatial coverage
#' required relative to the reference bounding box. Default is `0.99`.
#'
#' @returns
#' A list containing:
#' \itemize{
#'   \item `mesh`: reconstructed surface as a `mesh3d` object.
#'   \item `bin`: processed binning object.
#'   \item `contours`: disconnected surfaces generated by Marching Cubes, ordered from
#'   largest to smallest.
#'   \item `params`: parameters used during reconstruction.
#' }
#'
#' @details
#' Linear binning is performed with [npsp::binning()] and the grid coordinates are
#' obtained with [npsp::coordvalues()]. Low-density nodes are removed and high-density
#' weights are truncated before extracting the isosurface with [misc3d::contour3d()].
#'
#' When `zeroBorder = TRUE`, one zero-valued layer is added on both sides of the X
#' and Z directions to facilitate surface closure.
#'
#' If several disconnected surfaces are produced, they are ordered by size and progressively
#' merged until the reconstructed surface reaches `coverageTol` times the dimensions
#' of the reference bounding box.
#'
#' @seealso [npsp::binning()], [npsp::coordvalues()], [misc3d::contour3d()], [rgl::tmesh3d()]
#'
#' @examples
#' \dontrun{
#' # Load the theoretical CAD model
#' data("cad", package = "dimControl")
#'
#' # Prepare the theoretical panel mesh
#' meshTeor <- preparePanelMesh(cad)
#'
#' # Simulate panel points without floor points
#' panel <- simulatePanelFloorCloud(
#'   mesh = meshTeor,
#'   nPanel = 1e7,
#'   nFloor = 0,
#'   seed = 1
#' )
#'
#' # Reconstruct the mesh from the panel point cloud
#' result <- createMesh(
#'   panel = panel,
#'   resolNbin = c(4, 4, 2),
#'   zeroBorder = TRUE
#' )
#'
#' mesh <- result$mesh
#'
#' # Display point cloud and reconstructed mesh side by side
#' rgl::clear3d()
#' rgl::mfrow3d(1, 2)
#'
#' rgl::points3d(panel, col = "blue")
#' rgl::title3d("Panel point cloud", level = 4)
#'
#' rgl::next3d()
#' rgl::shade3d(mesh, col = "lightgray")
#' rgl::title3d("Reconstructed mesh", level = 4)
#' }
#'
#' @importFrom npsp binning coordvalues
#' @importFrom rgl tmesh3d
#' @importFrom utils capture.output getFromNamespace
#'
#' @export
createMesh <- function(panel,
                               resolNbin = c(4, 4, 2),
                               meshCad = NULL,
                               zeroBorder = FALSE,
                               kFactor = NULL,
                               truncFactor = 3.5,
                               levelFactor = 0.99,
                               coverageTol = 0.99) {

  panel <- as.matrix(panel)

  if (!is.numeric(panel))
    stop("Argument 'panel' must be numeric")

  if (ncol(panel) != 3)
    stop("Argument 'panel' must have three columns: x, y and z")

  if (anyNA(panel))
    stop("Argument 'panel' contains NA values")

  if (length(resolNbin) != 3 || any(resolNbin <= 0))
    stop("Argument 'resolNbin' must be a positive numeric vector of length 3")

  if (!is.logical(zeroBorder) || length(zeroBorder) != 1)
    stop("Argument 'zero_border' must be TRUE or FALSE")

  if (coverageTol <= 0 || coverageTol > 1)
    stop("Argument 'coverage_tol' must be greater than 0 and less than or equal to 1")

  # Point cloud dimensions
  dimLen <- apply(panel, 2, function(x) diff(range(x)))

  # Number of bins in each spatial direction
  nBin <- trunc(dimLen / resolNbin)
  nBin <- pmax(nBin, 2)

  # Linear binning
  bin <- npsp::binning(x = panel, nbin = nBin, type = "linear")
  bin$data <- NULL

  # Add one external zero-valued layer on the four sides:
  # left/right (X) and bottom/top (Z)
  if (zeroBorder) {
    dims <- bin$grid$n
    newDims <- dims + c(2, 0, 2)

    binwExt <- array(0, dim = newDims)

    binwExt[
      2:(dims[1] + 1),
      ,
      2:(dims[3] + 1)
    ] <- bin$binw

    bin$binw <- binwExt
    bin$grid$n <- newDims

    # Extend X limits
    bin$grid$min[1] <- bin$grid$min[1] - bin$grid$lag[1]
    bin$grid$max[1] <- bin$grid$max[1] + bin$grid$lag[1]

    # Extend Z limits
    bin$grid$min[3] <- bin$grid$min[3] - bin$grid$lag[3]
    bin$grid$max[3] <- bin$grid$max[3] + bin$grid$lag[3]
  }

  bin$grid$dimnames <- c("X", "Y", "Z")

  # Automatic tolerance factor
  if (is.null(kFactor)) {

    if (all(resolNbin == c(4, 4, 4))) {
      kFactor <- 0.1
    } else if (
      all(resolNbin == c(2, 2, 2)) ||
      all(resolNbin == c(4, 4, 2))
    ) {
      kFactor <- 0.05
    } else {
      kFactor <- 0.05
      warning(
        "No specific rule for 'resolNbin'. Using kFactor = 0.05"
      )
    }
  }

  # Non-empty binning nodes
  w <- bin$binw[bin$binw > 0]

  if (length(w) == 0)
    stop("The binning object has no positive weights")

  # Remove low weights
  tol <- (nrow(panel) / length(w)) * kFactor
  bin$binw[bin$binw <= tol] <- 0

  # Truncate high weights
  truncValue <- truncFactor * tol
  bin$binw[bin$binw > truncValue] <- truncValue

  # Marching Cubes density level
  levelBin <- levelFactor * truncValue

  # Binning coordinates
  coorval <- npsp::coordvalues(bin)

  # Marching Cubes
  utils::capture.output({

    contours <- with(
      coorval,
      misc3d::contour3d(
        bin$binw,
        level = levelBin,
        X, Y, Z,
        draw = FALSE,
        separate = TRUE
      )
    )

  })

  if (length(contours) == 0)
    stop("Marching Cubes did not generate any mesh")

  # Bounding box of a Triangles3D object
  triangleBbox <- function(x) {
    vertices <- rbind(x$v1, x$v2, x$v3)
    apply(vertices, 2, range)
  }

  # Order disconnected components from largest to smallest
  contours <- contours[
    order(sapply(contours, function(x) nrow(x$v1)), decreasing = TRUE)]

  # Dimensions used as reference for mesh coverage
  if (is.null(meshCad)) {
    refDim <- dimLen
  } else {
    if (!inherits(meshCad, "mesh3d"))
      stop("Argument 'meshCad' must be an object of class 'mesh3d'")

    cadVertices <- t(meshCad$vb[1:3, , drop = FALSE])
    cadBbox <- apply(cadVertices, 2, range)
    refDim <- cadBbox[2, ] - cadBbox[1, ]
  }

  # Merge disconnected components until the required coverage is reached
  surface <- NULL

  for (currentSurface in contours) {
    if (is.null(surface)) {
      surface <- currentSurface
    } else {
      surface$v1 <- rbind(surface$v1, currentSurface$v1)
      surface$v2 <- rbind(surface$v2, currentSurface$v2)
      surface$v3 <- rbind(surface$v3, currentSurface$v3)
    }

    currentBbox <- triangleBbox(surface)
    currentDim <- currentBbox[2, ] - currentBbox[1, ]

    if (all(currentDim >= refDim * coverageTol))
      break
  }

  # Convert Triangles3D to mesh3d
  t2ve <- utils::getFromNamespace("t2ve", "misc3d")

  mesh0 <- t2ve(surface)

  mesh <- rgl::tmesh3d(
    vertices = mesh0[["vb"]],
    indices = mesh0[["ib"]]
  )

  return(
    list(
      mesh = mesh,
      bin = bin,
      contours = contours,
      params = list(
        resolNbin = resolNbin,
        nBin = nBin,
        zeroBorder = zeroBorder,
        kFactor = kFactor,
        tol = tol,
        truncFactor = truncFactor,
        truncValue = truncValue,
        levelFactor = levelFactor,
        levelBin = levelBin,
        coverageTol = coverageTol
      )
    )
  )
}
