#' Simulated point cloud of a steel panel
#'
#' This dataset contains a synthetic point cloud generated from a processed theoretical
#' CAD mesh of a steel panel.
#'
#' Points are sampled over the mesh triangles with probability proportional to their
#' area, and truncated Gaussian noise is added to simulate the uncertainty inherent
#' to 3D scanning.
#'
#' The dataset is intended for testing, comparative evaluation, and demonstration of
#' dimensional control algorithms.
#'
#' @docType data
#' @name panelPoints
#' @format A numeric matrix with 5,000,000 rows and 3 columns:
#' \describe{
#'   \item{X}{X coordinate of the point}
#'   \item{Y}{Y coordinate of the point}
#'   \item{Z}{Z coordinate of the point}
#' }
#'
#' @details
#' The point cloud is generated by sampling a fixed number of points over the triangles
#' of a theoretical CAD mesh representing the surface of a steel panel. Points are
#' assigned to each triangle with probability proportional to its area. Truncated
#' Gaussian noise with zero mean and bounded support is added independently to each
#' coordinate to represent scanning uncertainty.
#'
#' @source
#' Simulated data generated from a processed theoretical CAD model.
NULL
