#' Simulate floor point cloud
#'
#' Simulates a floor point cloud around the bounding box of a 3D object point
#' cloud.
#'
#' @param object Numeric matrix with three columns (`X`, `Y`, `Z`) containing
#' the object point cloud.
#' @param n Number of floor points to simulate.
#' @param gap Non-negative numeric value specifying the vertical distance
#' between the lowest point of the object and the reference floor height.
#' @param margin Positive numeric value specifying the width of the floor region
#' around the object in the X and Y directions.
#' @param rgen Random number generator used to perturb the floor height. By
#' default, [rtnorm()] is used. [rtri()] is also provided by `dimControl`,
#' although any random number generator can be supplied.
#' @param ... Additional arguments passed to `rgen`.
#'
#' @returns
#' A numeric matrix with `n` rows and three columns (`X`, `Y`, `Z`) containing
#' the simulated floor point cloud.
#'
#' @details
#' The floor is simulated in four rectangular regions surrounding the X-Y
#' bounding box of `object`: left, right, bottom, and top.
#'
#' The reference floor height is defined as the minimum Z coordinate of the
#' object minus `gap`. Random noise generated by `rgen` is then added to this
#' reference height.
#'
#' `dimControl` provides [rtnorm()] and [rtri()] as random number generators
#' that can be used to model the random perturbation. Other random number
#' generators can also be supplied through `rgen`, provided that their first
#' argument specifies the number of values to generate. Distribution-specific
#' parameters are passed through `...`.
#'
#' @seealso [simulateCloud()], [rtnorm()], [rtri()]
#'
#' @export
simulateFloor <- function(object,
                          n,
                          gap,
                          margin,
                          rgen = rtnorm,
                          ...) {

  # Validate input arguments
  if (!is.matrix(object) || !is.numeric(object) || ncol(object) != 3)
    stop("Argument 'object' must be a numeric matrix with three columns")

  if (length(n) != 1 || !is.numeric(n) || is.na(n) || n <= 0)
    stop("Argument 'n' must be a positive number")

  if (length(gap) != 1 || !is.numeric(gap) || is.na(gap) || gap < 0)
    stop("Argument 'gap' must be a non-negative number")

  if (length(margin) != 1 || !is.numeric(margin) || is.na(margin) || margin <= 0)
    stop("Argument 'margin' must be a positive number")

  if (!is.function(rgen))
    stop("Argument 'rgen' must be a function")

  n <- as.integer(n)

  # Object bounding box
  xRange <- range(object[, "X"])
  yRange <- range(object[, "Y"])
  zRange <- range(object[, "Z"])

  # Extended floor limits
  xMinExt <- xRange[1] - margin
  xMaxExt <- xRange[2] + margin
  yMinExt <- yRange[1] - margin
  yMaxExt <- yRange[2] + margin

  # Number of floor points in each external region
  nLeft <- nRight <- nBottom <- round(n * 0.25)
  nTop <- n - nLeft - nRight - nBottom

  # Simulate left floor region
  floorLeft <- cbind(
    X = stats::runif(nLeft, xMinExt, xRange[1]),
    Y = stats::runif(nLeft, yMinExt, yMaxExt)
  )

  # Simulate right floor region
  floorRight <- cbind(
    X = stats::runif(nRight, xRange[2], xMaxExt),
    Y = stats::runif(nRight, yMinExt, yMaxExt)
  )

  # Simulate bottom floor region
  floorBottom <- cbind(
    X = stats::runif(nBottom, xRange[1], xRange[2]),
    Y = stats::runif(nBottom, yMinExt, yRange[1])
  )

  # Simulate top floor region
  floorTop <- cbind(
    X = stats::runif(nTop, xRange[1], xRange[2]),
    Y = stats::runif(nTop, yRange[2], yMaxExt)
  )

  # Combine floor regions
  floor <- rbind(floorLeft, floorRight, floorBottom, floorTop)

  # Reference floor height
  zFloor <- zRange[1] - gap

  # Add random noise to floor height
  floor <- cbind(floor, Z = zFloor + rgen(nrow(floor), ...))

  floor
}


#' Simulate 3D point cloud
#'
#' Simulates a 3D point cloud by sampling points from a triangular mesh and
#' adding random measurement noise. Optionally, a floor point cloud can be
#' generated around the object.
#'
#' @param mesh `mesh3d` object representing the surface from which points are
#' sampled.
#' @param n Number of points to sample from `mesh`.
#' @param rgen Random number generator used to generate measurement noise. By
#' default, [rtnorm()] is used. [rtri()] is also provided by `dimControl`,
#' although any random number generator can be supplied.
#' @param floor Optional list specifying the floor simulation parameters,
#' corresponding to arguments `n`, `gap`, and `margin` of the [simulateFloor()]
#' function (see examples below). The element `n` is required, whereas `gap` and
#' `margin` are optional and default to 2 and 20, respectively. If `NULL`
#' (default), no floor is generated.
#' @param ... Additional arguments passed to `rgen`. The same arguments are
#' used to generate random noise for both the object and the floor.
#'
#' @returns
#' A numeric matrix with three columns (`X`, `Y`, `Z`) containing the simulated
#' point cloud.
#'
#' @details
#' Points are sampled from `mesh` using [sampleMesh()] and independently
#' perturbed in the X, Y, and Z directions using random values generated by
#' `rgen`.
#'
#' By default, [rtnorm()] is used to generate the measurement noise.
#' `dimControl` also provides [rtri()] as an alternative random number generator.
#' Other random number generators can be supplied through `rgen`, with their
#' distribution-specific parameters passed through `...`.
#'
#' If `floor` is not `NULL`, a floor point cloud is generated using
#' [simulateFloor()]. The list element `n` specifies the number of floor points
#' and is required. The elements `gap` and `margin` are optional and, if not
#' supplied, default to 2 and 20, respectively.
#'
#' The same random number generator specified by `rgen` and the same
#' distribution-specific parameters supplied through `...` are used to generate
#' random noise for both the object and the floor.
#'
#' @examples
#' data("cad", package = "dimControl")
#'
#' # Truncated normal noise (default generator)
#' set.seed(1)
#' dataNorm <- simulateCloud(mesh = cad, n = 1e5, rgen = rtnorm, mean = 0, sd = 0.2,
#'                           a = -0.5, b = 0.5, floor = list(n = 5e3))
#' head(dataNorm)
#'
#' # Represent the simulated point cloud
#' open3d() # Alternatively, use `legendplot::new3d()` to clear the current device or open a new one
#' points3d(dataNorm, col = "gray", alpha = 0.1)
#'
#' # Triangular noise
#' set.seed(1)
#' dataTri <- simulateCloud(mesh = cad, n = 1e5, rgen = rtri, min = -0.5, max = 0.5)
#' head(dataTri)
#'
#' # Represent the simulated point cloud
#' open3d() # Alternatively, use `legendplot::new3d()` to clear the current device or open a new one
#' points3d(dataTri, col = "gray", alpha = 0.1)
#'
#' @seealso [simulateFloor()], [rtnorm()], [rtri()]
#'
#' @export
simulateCloud <- function(mesh,
                          n,
                          rgen = rtnorm,
                          floor = NULL,
                          ...) {

  # Validate input arguments
  if (!inherits(mesh, "mesh3d"))
    stop("Argument 'mesh' must be an object of class 'mesh3d'")

  if (length(n) != 1 || !is.numeric(n) || is.na(n) || n <= 0)
    stop("Argument 'n' must be a positive number")

  if (!is.function(rgen))
    stop("Argument 'rgen' must be a function")

  if (!is.null(floor) && !is.list(floor))
    stop("Argument 'floor' must be NULL or a list")

  n <- as.integer(n)

  # Sample points from the mesh
  object <- t(sampleMesh(mesh, n))

  # Generate random noise
  noise <- rgen(n * 3, ...)

  # Add noise independently to X, Y and Z
  object <- object + noise
  colnames(object) <- c("X", "Y", "Z")

  # Return only object points when no floor is requested
  if (is.null(floor)) return(object)

  # Validate floor parameters
  if (is.null(floor$n))
    stop("Argument 'floor' must contain an element named 'n'")

  # Set default floor parameters
  gap <- if (is.null(floor$gap)) 2 else floor$gap
  margin <- if (is.null(floor$margin)) 20 else floor$margin

  # Simulate floor points
  floorCloud <- simulateFloor(object = object, n = floor$n, gap = gap,
                              margin = margin, rgen = rgen, ...)

  # Combine object and floor points
  rbind(object, floorCloud)
}
