

# simulateCloud(mesh, n, rgen = rtnorm, nfloor = 0, zfloor, mfloor, ... )
# ... parámetros adicionales de rgen


#' Simulate floor point cloud
#'
#' Simulates a floor point cloud around the bounding box of a 3D object point cloud.
#'
#' @param object Numeric matrix with three columns (`X`, `Y`, `Z`) containing the
#' object point cloud.
#' @param n Number of floor points to simulate.
#' @param gap Non-negative numeric value specifying the vertical distance between
#' the lowest point of the object and the reference floor height.
#' @param margin Positive numeric value specifying the width of the floor region around
#' the object in the X and Y directions.
#' @param rgen Random number generator used to perturb the floor height. By default,
#' a truncated normal distribution is used.
#' @param ... Additional arguments passed to `rgen`.
#'
#' @returns
#' A numeric matrix with `n` rows and three columns (`X`, `Y`, `Z`) containing the
#' simulated floor point cloud.
#'
#' @details
#' The floor is simulated in four rectangular regions surrounding the X-Y bounding
#' box of `object`: left, right, bottom, and top.
#'
#' The reference floor height is defined as the minimum Z coordinate of the object
#' minus `gap`. Random noise generated by `rgen` is then added to this reference height.
#'
#' By default, the noise follows a truncated normal distribution with mean 0, standard
#' deviation 0.2, and lower and upper bounds of -0.5 and 0.5, respectively.
#'
#' @export
simulateFloor <- function(object,
                          n,
                          gap,
                          margin,
                          rgen = .rtnormDefault,
                          ...) {

  # Validate input arguments
  if (!is.matrix(object) || !is.numeric(object) || ncol(object) != 3)
    stop("Argument 'object' must be a numeric matrix with three columns")

  if (length(n) != 1 || !is.numeric(n) || is.na(n) || n <= 0)
    stop("Argument 'n' must be a positive number")

  if (length(gap) != 1 || !is.numeric(gap) || is.na(gap) || gap < 0)
    stop("Argument 'gap' must be a non-negative number")

  if (length(margin) != 1 || !is.numeric(margin) || is.na(margin) || margin <= 0)
    stop("Argument 'margin' must be a positive number")

  if (!is.function(rgen))
    stop("Argument 'rgen' must be a function")

  n <- as.integer(n)

  # Object bounding box
  xRange <- range(object[, "X"])
  yRange <- range(object[, "Y"])
  zRange <- range(object[, "Z"])

  # Extended floor limits
  xMinExt <- xRange[1] - margin
  xMaxExt <- xRange[2] + margin
  yMinExt <- yRange[1] - margin
  yMaxExt <- yRange[2] + margin

  # Number of floor points in each external region
  nLeft <- nRight <- nBottom <- round(n * 0.25)
  nTop <- n - nLeft - nRight - nBottom

  # Simulate left floor region
  floorLeft <- cbind(
    X = stats::runif(nLeft, xMinExt, xRange[1]),
    Y = stats::runif(nLeft, yMinExt, yMaxExt)
  )

  # Simulate right floor region
  floorRight <- cbind(
    X = stats::runif(nRight, xRange[2], xMaxExt),
    Y = stats::runif(nRight, yMinExt, yMaxExt)
  )

  # Simulate bottom floor region
  floorBottom <- cbind(
    X = stats::runif(nBottom, xRange[1], xRange[2]),
    Y = stats::runif(nBottom, yMinExt, yRange[1])
  )

  # Simulate top floor region
  floorTop <- cbind(
    X = stats::runif(nTop, xRange[1], xRange[2]),
    Y = stats::runif(nTop, yRange[2], yMaxExt)
  )

  # Combine floor regions
  floor <- rbind(floorLeft, floorRight, floorBottom, floorTop)

  # Reference floor height
  zFloor <- zRange[1] - gap

  # Add random noise to floor height
  floor <- cbind(floor, Z = zFloor + rgen(nrow(floor), ...))

  floor
}


#' Simulate 3D point cloud
#'
#' Simulates a 3D point cloud by sampling points from a triangular mesh and adding
#' random measurement noise. Optionally, a floor point cloud can be generated around
#' the object.
#'
#' @param mesh `mesh3d` object representing the surface from which points are sampled.
#' @param n Number of points to sample from `mesh`.
#' @param rgen Random number generator used to generate measurement noise. By default,
#' a truncated normal distribution is used.
#' @param floor Optional list specifying the floor simulation parameters. It must contain
#' `n`, the number of floor points, and may contain `gap` and `margin`. If `NULL`, no
#' floor is generated. Default is `NULL`.
#' @param ... Additional arguments passed to `rgen`.
#'
#' @returns
#' A numeric matrix with three columns (`X`, `Y`, `Z`) containing the simulated point
#' cloud.
#'
#' @details
#' Points are sampled from `mesh` using [sampleMesh()] and independently perturbed
#' in the X, Y and Z directions using random values generated by `rgen`.
#'
#' By default, the measurement noise follows a truncated normal distribution with
#' mean 0, standard deviation 0.2, and lower and upper bounds of -0.5 and 0.5, respectively.
#'
#' If `floor` is not `NULL`, a floor point cloud is generated using [simulateFloor()].
#' The list element `n` specifies the number of floor points. If `gap` or `margin` are
#' not supplied, values of 2 and 20, respectively, are used.
#'
#' The same random number generator and additional parameters supplied through `...`
#' are used for the object and floor.
#'
#' @examples
#' library(rgl)
#'
#' data("cad", package = "dimControl")
#'
#' data <- simulateCloud(mesh = cad, n = 1e5, floor = list(n = 5e3, gap = 2,
#'                       margin = 20))
#' head(data)
#'
#' # Represent the simulated point cloud
#' open3d() # Alternatively, use `legendplot::new3d()` to clear the current device or open a new one
#' points3d(data, col = "gray")
#'
#' @export
simulateCloud <- function(mesh,
                          n,
                          rgen = .rtnormDefault,
                          floor = NULL,
                          ...) {

  # Validate input arguments
  if (!inherits(mesh, "mesh3d"))
    stop("Argument 'mesh' must be an object of class 'mesh3d'")

  if (length(n) != 1 || !is.numeric(n) || is.na(n) || n <= 0)
    stop("Argument 'n' must be a positive number")

  if (!is.function(rgen))
    stop("Argument 'rgen' must be a function")

  if (!is.null(floor) && !is.list(floor))
    stop("Argument 'floor' must be NULL or a list")

  n <- as.integer(n)

  # Sample points from the mesh
  object <- t(sampleMesh(mesh, n))

  # Generate random noise
  noise <- rgen(n * 3, ...)

  # Add noise independently to X, Y and Z
  object <- object + noise
  colnames(object) <- c("X", "Y", "Z")

  # Return only object points when no floor is requested
  if (is.null(floor)) return(object)

  # Validate floor parameters
  if (is.null(floor$n))
    stop("Argument 'floor' must contain an element named 'n'")

  # Set default floor parameters
  gap <- if (is.null(floor$gap)) 2 else floor$gap
  margin <- if (is.null(floor$margin)) 20 else floor$margin

  # Simulate floor points
  floorCloud <- simulateFloor(object = object, n = floor$n, gap = gap,
                              margin = margin, rgen = rgen, ...)

  # Combine object and floor points
  rbind(object, floorCloud)
}
